### ISSUE TITLE
Cannot use an isolated steam account to download ArmA 3 workshop items.

### ISSUE THREAD

**Issue by farhannysf** [jannes-io/steam-workshop-downloader#1]
Quoting from Configuration section on README.md below:

---
## Configuration
We highly recommend running this script on an isolated steam account rather than a personal account.
You must also **either disable steam guard, or run and log in to steamcmd at least once** to cache the steam guard code.

Here you can find an example for cba and ace.
```json
{
  "username": "somefakename",
  "password": "somefakepassword",
  "steamCMD": "(C:)\\path\\to\\steamcmd(.exe)",
  "outDir": "(C:)\\path\\to\\mods",
  "appid": "107410",
  "workshopItems": {
    "@cba": "450814997",
    "@ace3": "463939057"
  },
  "includes": {
    "@ace3": [
      "optionals\\@ace_realisticdispersion",
      "optionals\\@ace_particles"
    ]
  }
}
```
---

You cannot use an isolated Steam account that does not own ArmA 3 game to download its workshop items.

This will result in steamCMD outputting error when attempting to download the specified ArmA 3 workshop items in config.json.

**Comment by jannes-io** [comment]
You are correct, you do need to own the game on this isolated steam account. In most communities the cost of a copy of Arma 3 from some online key store is negligible.

![image](https://user-images.githubusercontent.com/9079379/195055442-43ddaac9-2d9b-421a-8540-aad52632d006.png)
