### ISSUE TITLE
Expired Game

### ISSUE THREAD

**Issue by jtopaz1** [jannes-io/steam-workshop-downloader#2]
I tried to download an expired game workshop [Google Game Builder (appId=929860)] using steam-workshop-downloader. However, it failed.
I don't have this game in my account because when this game already expired when I found it. Is there any solution?

**Comment by jannes-io** [comment]
Unfortunately no. You need to own a copy of the game to download workshop items. This is a restriction from steam to prevent pirating workshop items.
